version: "3.8"

services:
  krushidhan-erp:
    build: .
    container_name: krushidhan_erp_app
    restart: always
    ports:
      - "8008:8008"
    volumes:
      - ./data:/app/data
      - ./backups:/app/backups
    environment:
      - PORT=8008
      - PYTHONUNBUFFERED=1
